name: flutter_rich_html
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  html: any
  flutter:
    sdk: flutter
  extended_text_field:
    git:
      url: git://github.com/fluttercandies/extended_text_field.git
      ref: master
  extended_text_library: ^4.0.0
  flutter_bubble:
    git:
      url: git://github.com/ACE-YANGCE/Flutter_Bubble.git
  code_editor: 1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass